name: "Build"
on: [push]
jobs:
  linux-clang-build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        clang: [6, 8, 10, 11]
    steps:
      - uses: actions/checkout@v2
        with:
            # Nix Flakes doesn't work on shallow clones
            fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes ca-references
      - name: nix build hobbesPackages/clang-${{ matrix.clang }}/hobbes
        run: |
          nix build .#hobbesPackages/clang-${{ matrix.clang }}/hobbes
          nix log  .#hobbesPackages/clang-${{ matrix.clang }}/hobbes &> ${{ matrix.os }}-clang-${{ matrix.clang }}-hobbes.log
      - name: upload log ${{ matrix.os }}-clang-${{ matrix.clang }}-hobbes.log
        uses: actions/upload-artifact@v1
        with:
          name: output-log-file
          path: ${{ matrix.os }}-clang-${{ matrix.clang }}-hobbes.log
  linux-gcc-build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        gcc: [10]
        llvm: [6, 8, 10, 11]
    steps:
      - uses: actions/checkout@v2
        with:
            # Nix Flakes doesn't work on shallow clones
            fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes ca-references
      - name: nix build hobbesPackages/clang-${{ matrix.clang }}/hobbes
        run: |
          nix build .#hobbesPackages/gcc-${{ matrix.gcc }}/llvm-${{ matrix.llvm }}/hobbes
          nix log  .#hobbesPackages/gcc-${{ matrix.gcc }}/llvm-${{ matrix.llvm }}/hobbes &> ${{ matrix.os }}-gcc-${{ matrix.gcc }}-llvm-${{ matrix.llvm }}-hobbes.log
      - name: upload log ${{ matrix.os }}-gcc-${{ matrix.gcc }}-llvm-${{ matrix.llvm }}-hobbes.log
        uses: actions/upload-artifact@v1
        with:
          name: output-log-file
          path: ${{ matrix.os }}-gcc-${{ matrix.gcc }}-llvm-${{ matrix.llvm }}-hobbes.log

